version: 0.2

env:
  variables:
    DISTRIBUTION_ID: ${DISTRIBUTION_ID}
    BUCKET_NAME: ${BUCKET_NAME}

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn install
  build:
    commands:
      - echo Build started on 'date'
      - yarn run build
  post_build:
    commands:
      - aws s3 sync ./build 's3://${BUCKET_NAME}/'
      - aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --path '/*'
artifacts:
  files:
    - "build/*"
    - "build/**/*"